#!/usr/bin/env bash
# Copies the old mcil.net investor reports into the site's Cloud Storage bucket.
#
# Run it in Google Cloud Shell (the >_ button at the top of console.cloud.google.com):
#
#     bash copy-to-bucket.sh YOUR-BUCKET-NAME
#
# Use the same bucket as the website's GCS_BUCKET setting. If the site also sets
# GCS_PREFIX, pass that as a second argument.
#
# It downloads each file from mcil.net into Cloud Shell, then uploads the lot to
# gs://YOUR-BUCKET-NAME/reports/. Nothing touches your own computer. It is safe
# to run again: files already downloaded are skipped, so a run cut short picks
# up where it stopped.
#
# Generated by tools/old-reports/build.py — edit that, not this file.

set -uo pipefail

BUCKET="${1:-}"
PREFIX="${2:-}"
if [ -z "$BUCKET" ]; then
  echo "Usage: bash copy-to-bucket.sh YOUR-BUCKET-NAME [GCS_PREFIX]"
  exit 1
fi
PREFIX="${PREFIX#/}"; PREFIX="${PREFIX%/}"
DEST="gs://${BUCKET}/${PREFIX:+$PREFIX/}"

WORK="$HOME/mcil-old-reports"
mkdir -p "$WORK/reports"
cd "$WORK" || exit 1
: > failed.txt

echo "Step 1 of 2: downloading __COUNT__ files from mcil.net (about 740 MB, usually 5-15 minutes)..."
done_count=0
while IFS=$'\t' read -r path url; do
  [ -z "$path" ] && continue
  done_count=$((done_count + 1))
  file="reports/$path"
  if [ -s "$file" ]; then continue; fi
  mkdir -p "$(dirname "$file")"
  # The old server drops connections now and then, so retry generously.
  if curl -fsSL --retry 8 --retry-all-errors --retry-delay 3 --max-time 300 \
       -o "$file.part" "$url"; then
    # A PDF that does not start with %PDF is an error page, not the report.
    if [[ "$file" == *.pdf ]] && [ "$(head -c 4 "$file.part")" != "%PDF" ]; then
      rm -f "$file.part"
      echo "$path	$url	(not a PDF)" >> failed.txt
    else
      mv "$file.part" "$file"
    fi
  else
    rm -f "$file.part"
    echo "$path	$url" >> failed.txt
  fi
  if [ $((done_count % 50)) -eq 0 ]; then echo "  $done_count / __COUNT__"; fi
done <<'LIST'
__LIST__
LIST

if [ -s failed.txt ]; then
  echo
  echo "These could not be downloaded:"
  cat failed.txt
  echo
  echo "Run the same command again to retry them. Uploading the rest now."
fi

echo "Step 2 of 2: uploading to ${DEST}reports/ ..."
gcloud storage cp -r "$WORK/reports" "$DEST" \
  --cache-control="public, max-age=86400" \
  --content-disposition="attachment" || {
  echo "Upload failed. Check the bucket name, then run the same command again."
  exit 1
}

count=$(find "$WORK/reports" -type f ! -name '*.part' | wc -l)
echo
echo "Done: $count files are in ${DEST}reports/"
if [ -s failed.txt ]; then
  echo "$(wc -l < failed.txt) still missing — run the command again to retry them."
else
  echo "Everything copied. You can delete $WORK now: rm -rf $WORK"
fi
